# Generated by Django 4.2.5 on 2024-03-05 20:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Bauman_Consulting', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactForm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('thema', models.CharField(max_length=100)),
                ('vorname', models.CharField(max_length=100)),
                ('nachname', models.CharField(max_length=100)),
                ('firma', models.CharField(max_length=100)),
                ('telephone', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=254)),
                ('betreff', models.CharField(max_length=100)),
                ('nachricht', models.TextField()),
            ],
        ),
        migrations.DeleteModel(
            name='ContactMessage',
        ),
    ]
