# Generated by Django 4.2.6 on 2024-03-08 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Bauman_Consulting', '0003_kaufenform'),
    ]

    operations = [
        migrations.RenameField(
            model_name='kaufenform',
            old_name='thema',
            new_name='Hausnummer',
        ),
        migrations.AddField(
            model_name='kaufenform',
            name='Ort',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='kaufenform',
            name='PLZ',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='kaufenform',
            name='Strasse',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
    ]
