# Generated by Django 4.2.5 on 2024-03-20 21:20

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('Bauman_Consulting', '0004_rename_thema_kaufenform_hausnummer_kaufenform_ort_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactform',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
