# Generated by Django 4.2.5 on 2024-05-14 20:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Bauman_Consulting', '0005_contactform_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='kaufenform',
            name='Hausnummer_l',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='kaufenform',
            name='Ort_l',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='kaufenform',
            name='PLZ_l',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='kaufenform',
            name='Strasse_l',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='kaufenform',
            name='betreff_l',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='kaufenform',
            name='email_l',
            field=models.EmailField(default='', max_length=254),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='kaufenform',
            name='firma_l',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='kaufenform',
            name='nachname_l',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='kaufenform',
            name='nachricht_l',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='kaufenform',
            name='telephone_l',
            field=models.CharField(default='', max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='kaufenform',
            name='vorname_l',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
    ]
