# Generated by Django 4.2.5 on 2024-06-02 16:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Bauman_Consulting', '0006_kaufenform_hausnummer_l_kaufenform_ort_l_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='kaufenform',
            old_name='Hausnummer_l',
            new_name='hausnummer_l',
        ),
        migrations.RenameField(
            model_name='kaufenform',
            old_name='Ort_l',
            new_name='ort_l',
        ),
        migrations.RenameField(
            model_name='kaufenform',
            old_name='PLZ_l',
            new_name='plz_l',
        ),
        migrations.RenameField(
            model_name='kaufenform',
            old_name='Strasse_l',
            new_name='strasse_l',
        ),
    ]
