# Generated by Django 4.2.5 on 2024-06-02 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Bauman_Consulting', '0007_rename_hausnummer_l_kaufenform_hausnummer_l_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='kaufenform',
            name='Hausnummer',
        ),
        migrations.RemoveField(
            model_name='kaufenform',
            name='Ort',
        ),
        migrations.RemoveField(
            model_name='kaufenform',
            name='PLZ',
        ),
        migrations.RemoveField(
            model_name='kaufenform',
            name='Strasse',
        ),
        migrations.AlterField(
            model_name='kaufenform',
            name='betreff',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='kaufenform',
            name='betreff_l',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='kaufenform',
            name='email',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AlterField(
            model_name='kaufenform',
            name='email_l',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AlterField(
            model_name='kaufenform',
            name='firma',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='kaufenform',
            name='firma_l',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='kaufenform',
            name='hausnummer_l',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='kaufenform',
            name='nachname',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='kaufenform',
            name='nachname_l',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='kaufenform',
            name='nachricht',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='kaufenform',
            name='nachricht_l',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='kaufenform',
            name='ort_l',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='kaufenform',
            name='plz_l',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='kaufenform',
            name='strasse_l',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='kaufenform',
            name='telephone',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='kaufenform',
            name='telephone_l',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='kaufenform',
            name='vorname',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='kaufenform',
            name='vorname_l',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='kaufenform',
            name='hausnummer',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='kaufenform',
            name='ort',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='kaufenform',
            name='plz',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='kaufenform',
            name='strasse',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
